import { NextRequest, NextResponse } from 'next/server';
import { extractVideoId } from '@/lib/youtube/parser';

export async function POST(request: NextRequest) {
  try {
    const { url, videoId } = await request.json();

    if (!url && !videoId) {
      return NextResponse.json(
        { success: false, error: 'URL or video ID is required' },
        { status: 400 }
      );
    }

    const id = videoId || extractVideoId(url);

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Invalid YouTube URL' },
        { status: 400 }
      );
    }

    // In production, integrate with YouTube subtitle API or third-party service
    // For now, return mock subtitle data
    const mockSubtitles = [
      {
        language: 'English',
        languageCode: 'en',
        url: `https://youtube.com/api/timedtext?v=${id}&lang=en`,
        isAutoGenerated: false,
      },
      {
        language: 'Spanish',
        languageCode: 'es',
        url: `https://youtube.com/api/timedtext?v=${id}&lang=es`,
        isAutoGenerated: true,
      },
    ];

    return NextResponse.json({
      success: true,
      data: {
        videoId: id,
        subtitles: mockSubtitles,
      },
      message: 'Subtitles fetched successfully',
    });
  } catch (error) {
    console.error('Subtitle API error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}
