export type ToolType = 'video' | 'playlist' | 'subtitle' | 'thumbnail' | 'mp3' | 'shorts';

export interface YouTubeVideo {
  id: string;
  title: string;
  thumbnail: string;
  duration: string;
  channel: string;
  channelId: string;
  description?: string;
  viewCount?: string;
  uploadDate?: string;
  availableQualities?: string[];
}

export interface YouTubePlaylist {
  id: string;
  title: string;
  thumbnail: string;
  channelTitle: string;
  itemCount: number;
  videos: YouTubeVideo[];
}

export interface VideoQuality {
  quality: string;
  format: string;
  size?: string;
  url?: string;
}

export interface Subtitle {
  language: string;
  languageCode: string;
  url: string;
  isAutoGenerated: boolean;
}

export interface ThumbnailSize {
  quality: 'default' | 'medium' | 'high' | 'standard' | 'maxres';
  url: string;
  width: number;
  height: number;
}

export interface DownloadResult {
  success: boolean;
  url?: string;
  filename?: string;
  error?: string;
}

export interface APIResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}
